import solc from "solc";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const source = readFileSync("contracts/VWRPass.sol", "utf8");
const input = {
  language: "Solidity",
  sources: { "VWRPass.sol": { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    viaIR: true,
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};
const out = JSON.parse(solc.compile(JSON.stringify(input)));
const errors = (out.errors ?? []).filter((e) => e.severity === "error");
if (errors.length) { console.error(errors.map((e) => e.formattedMessage).join("\n")); process.exit(1); }
for (const w of (out.errors ?? [])) console.warn(w.formattedMessage?.split("\n")[0]);
const c = out.contracts["VWRPass.sol"].VWRPass;
mkdirSync("lib/generated", { recursive: true });
writeFileSync(
  "lib/generated/vwrpass.ts",
  `// Generated by scripts/compile.mjs — do not edit.\nexport const VWR_PASS_ABI = ${JSON.stringify(c.abi)} as const;\nexport const VWR_PASS_BYTECODE = "0x${c.evm.bytecode.object}" as const;\n`,
);
console.log("compiled OK — bytecode", c.evm.bytecode.object.length / 2, "bytes");
